#!/bin/sh
# expected to run as root
# perform WiFi custom setup updating ../hotspot/wifi.json
# and /etc/NetworkManager/system-connections/
# 1. If ../hotspot/wifi.json doesn't exist
# 	start a local WiFi hotspot named within $topdir/local_config with autoconnect-priority=-10
# 	scan for WiFi networks > ../hotspot/wifi.json
# 	enable a microdot web server to allow network choice
# 	on choice, connect to the desired network (network file will be created in
# 	/etc/NetworkManager/system-connections/)
# 2. If a working network definition exists in
# 	/etc/NetworkManager/system-connections/, connect to it
# 3. If the connection cannot be accessed, fall back to the hotspot, rescan and
# 	start the web server for network choice
here=$(dirname $0)
this=$(basename $0)
topdir=$(dirname $here)
hot_dir=$topdir/hotspot
application_ssid_file=$topdir/data/application_ssid	# written by network setup job
kill_file=$topdir/data/kill_file
net_file=${hot_dir}/data/wifi.json
# import the local_setup generated config
# contains hotspot_name and hotspot_password
. $topdir/local_config

# functions 

setup_hotspot()
{
	nmcli device wifi hotspot ssid "$hotspot_name" con-name "$hotspot_name" password "$hotspot_password" || return 1
	# testing shows that wpa-psk hotspot must have 8 char password or else
	nmcli connection modify "$hotspot_name" connection.autoconnect-priority -10 connection.autoconnect yes || return 1
	return 0
}

# start_application must contain everything required to set up and start the application

start_application()
{
	# this is why the service Type=forking
	# Type=simple kills child processes
	[ -x "$topdir/start_application" ] && nohup $topdir/start_application $topdir 0<&- &>/dev/null &
}

# MAIN Main main

# Conditional changes
# These are mainly for debugging during development and should not be 
# used for production

if [ "$desired_locale" ] ; then
	grep $desired_locale /etc/default/locale >/dev/null
	if [ $? -eq 0 ] ; then
		:
	else
		locale-gen
		# change the locale
		/usr/bin/raspi-config nonint do_change_locale $desired_locale
		# if the previous doesn't work, might have to
		# clear the locale
		# update-locale --no-checks LANG
		# then set
		# update-locale --no-checks LANG=en_US.UTF-8 UTF-8
	fi
fi 

if [ "$enable_ssh" ] ; then
	if [ $(/usr/bin/raspi-config nonint get_ssh) -eq 0 ] ; then
		:
	else
		# enable ssh
		/usr/bin/raspi-config nonint do_ssh 0
	fi
fi

if [ "$desired_timezone" ] ; then
	tz=$(cat /etc/timezone)
	if [ "$tz" = "$desired_timezone" ] ; then
		:
	else
		/usr/bin/raspi-config nonint do_change_timezone $desired_timezone
	fi
fi

if [ "$desired_wifi_country" ] ; then
	/usr/sbin/iw reg get | grep -q "country $desired_wifi_country"
	if [ $? -eq 0 ] ; then
		:
	else
		/usr/sbin/iw reg set $desired_wifi_country
	fi
fi 

# end of conditional changes

# unblock wifi
rfkill --output "TYPE,SOFT,HARD" --noheadings list wlan | read type soft hard
if [ "$soft" = "unblocked" -a "$hard" = "unblocked" ] ; then
	:
else
	rfkill unblock wifi
fi
nmcli --get-values "WIFI-HW,WIFI" radio | read line
if [ "$line" = "enabled:enabled" ] ; then
	:
else
	# turn on the wifi
	nmcli radio wifi on >/dev/null 2>&1 # >> $log
fi
sleep 5
nmcli --terse radio wifi # >> $log

# trixie: first boot after sd card creation wifi is unavailable

attempt=2
radio_state=$(nmcli --terse radio wifi)
while [ "$radio_state" != "enabled" ] ; do
	[ $attempt -gt 5 ] && { logit "Force reboot"	; shutdown -r now ; }
	nmcli radio wifi on >/dev/null 2>&1 # >> $log
	sleep 5
	radio_state=$(nmcli --terse radio wifi)
	attempt=$((attempt+1))
done

# nmcli device
# nmcli connection

if [ -f $application_ssid_file ] ; then
	desired_ssid=$(cat $application_ssid_file)
	# or $(grep -v "^#" $application_ssid_file) if we want comments in the file
	# short sleep here - we were checking before the interface had come up
	# or loop a bit
	sleep 5
	nmcli --terse device | grep -w wifi | grep -w connected | grep "$desired_ssid" > /dev/null
	if [ $? -eq 0 ] ; then
		start_application
		return 0
	else
		# killswitch should take care of this
		return 0
	fi
fi

if [ ! -f $net_file ] ; then
	setup_hotspot
	if [ $? -ne 0 ] ; then
		exit
	fi
fi

nmcli device wifi rescan >/dev/null 2>&1
sleep 5
l=0
while [ $l -le 5 ] 
do
	items=$(nmcli --terse device wifi list | wc -l)
	[ $items -gt 1 ] && break
	i=$((l+1))
	sleep 5
done
nmcli device wifi list >/dev/null 2>&1 # >> $log 2>&1
# pick up field 12 (signal strength) and filter out weak networks with strength
# less than 45
json="{ \"hotspot_name\": \"$hotspot_name\", \"preferred_ip\": \"\", \"access_points\": ["
# set IFS to nl to prevent word split on silly hotspot names
IFS='
'
for line in $(nmcli --terse device wifi list | cut -d: -f8,12)
do
	ap=$(echo $line|cut -d: -f1)
	# lose non-numerics if they turn up in field 12
	stren=$(echo $line|cut -d: -f2|sed 's/[^0-9]*//g')
	[ "$stren" ] || stren=0	# this will drop aps with non-numeric strength
	# arb choice of 45 to weed out weak aps
	if [ $stren -gt 45 ] ; then
		json="$json  \"$ap\","
	fi
done
unset IFS
json=$(echo $json | sed 's/,$/]}/')
# write a json file
echo $json > $net_file

# now start the webserver for initial WiFi configuration
nohup /usr/bin/python3 $hot_dir/cfg_webserver.py $topdir 0<&- &>/dev/null &
# if the user successfully connects to a wifi network, it should be added to system-connections and be active going forward...
# and finally, make cron re-read crontabs
pkill -HUP cron
