#!/usr/bin/sh
# 
# setup script to copy the local ./setup directory to
# /usr/local/setup on the SD card
# then run some customization
#
######################################################
usage() {
	echo "Usage: $0 -p 'SD card mount point' -t 'target directory on SD card' [ -s optional ssh key ]"  1>&2
	[ "$usage_errors" ] && echo "$usage_errors"
	exit 1
}

# required: local root
# required: sd card target dir
# optional: ssh key
# file system location where the sd card is mounted
local_ssh_key=
path_errors=''
usage_errors=''
while getopts ":p:t:s:" o; do
	case "${o}" in
		p) rootdir=${OPTARG}
			c1=$(echo $rootdir | cut -c1)
			if [ "$c1" = "-" ]  ; then
			  	path_errors="${path_errors}SD card mount point is required\n"
			elif [ ! "$c1" = "/" ] ; then
				path_errors="${path_errors}[$rootdir] is not a valid path\n"
			else
				[ -d "$rootdir" ] || { path_errors="${path_errors}SD card mount point [$rootdir] does not exist\n" ; }
			fi
			;;
		t) topdir=${OPTARG}
			c1=$(echo $topdir | cut -c1)
			if [ "$c1" = "-" ]  ; then
				path_errors="${path_errors}SD card target dir is required\n"
			elif [ ! "$c1" = "/" ] ; then
				path_errors="${path_errors}[$topdir] is not a valid path\n"
			fi
			# if [ -d "$rootdir" ] ; then
			#	[ -d "$rootdir/$topdir" ] || { usage_errors="${usage_errors}[$topdir] not found on SD card\n" ; }
			# fi
			;;
		s) local_ssh_key=${OPTARG}
			[ -f "$local_ssh_key" ] || { usage_errors="${usage_errors}ssh key file [$local_ssh_key] not found\n" ; }
			;;
		*) usage
			;;
	esac
done
shift $((OPTIND-1))
echo "rootdir [$rootdir]"
echo "topdir [$topdir]"
echo "local_ssh_key [$local_ssh_key]"
[ -z "$rootdir" ] || [ -z "$topdir" ] && usage
if [ -z "$path_errors" ] ; then 
	if [ ! -d "$rootdir$topdir" ] ; then
		upper_dir=$(dirname $rootdir$topdir)
		if [ ! -d "$upper_dir" ] ; then
			usage_errors="${usage_errors}[$upper_dir] not found on SD card\n"
		fi
		# usage_errors="${usage_errors}[$topdir] not found on SD card\n"
	fi
else
	usage_errors=${usage_errors}${path_errors}
fi
[ "$usage_errors" ] && usage

# config_file=./local_config
# echo "# generated by $(basename $0) for sd card creation" > $config_file
# echo "rootdir=$rootdir" >> $config_file
# echo "local_ssh_key=$local_ssh_key" >> $config_file
# 
# # and /usr/local/setup/systemd/cust-net on the SD card
# # cust-net will configure accordingly
# sd_config_file=./setup/local_config
# # change these as necessary
# desired_locale="en_US.UTF-8"
# desired_timezone="Africa/Johannesburg"
# desired_wifi_country="ZA"
# # configuring multiple devices? Use different hotspot names 
# hotspot_name="Hotspot"
# hotspot_pass="Hotspot-pass"
# 
# echo "# generated by setup script before sd card creation" > $sd_config_file
# echo "desired_locale=$desired_locale" >> $sd_config_file
# echo "desired_timezone=$desired_timezone" >> $sd_config_file
# echo "desired_wifi_country=$desired_wifi_country" >> $sd_config_file
# echo "hotspot_name=$hotspot_name" >> $sd_config_file
# echo "hotspot_pass=$hotspot_pass" >> $sd_config_file

# set execute permission on key files
# netmon

# change the _TARGET_ in systemd/cust-net.service
sed -s "s|_TARGET_|$topdir|g" ./setup/systemd/cust-net.template > ./setup/systemd/cust-net.service

mkdir $rootdir$topdir
cp -r ./setup/* $rootdir$topdir
ksh -x ./local_setup $rootdir $topdir $local_ssh_key
